const GENERIC_RESPONSE_MESSAGES = {
  INTERNAM_SERVER_ERROR: "Internal server error",
  SOMETHING_WENT_WRONG: "Something went wrong",
  PLEASE_TRY_AGAIN: "Please try again later",
  ROLE_IS_REQUIRED: "Role is required",
  USER_NOT_VERIFIED: "User is not verified",
  MOBILE_OR_PASSWORD_NOT_MATCHINF: "Mobile or password not matching",
  FIRST_NAME_REQUIRED: "First name is required",
  DOB: "Date of birth is required",
  MOBILE_IS_REQUIRED: "Mobile number is required",
  PASS_CONFIRMPASS_NOT_MATCHING: "Password and confirm is not matching",
  PASSWORD_IS_REQUIRED: "Password is required",
  CONFIRM_PASS_IS_REQUIRED: "Confirm password is required",
  MOBILE_IN_10_DIGIT: "Mobile numbe should be 10 digits",
  USER_ALREDY_EXIST: "User alredy exist",
  TOKEN_NOT_INSERTED: "Token not insered into database",
  OTP_NOT_MATCHING: "OTP not matching",
  OTP_USER_NOT_FOUND: "Otp or User is not found our database please try again later",
  OTP_REQUIRED: "Otp is required",
  USER_VERIFIED: "User is verified now",
  CATEGORY_NAME_REQUIRED: "Category name is required",
  LANGUAGE_REQUIRED: "Language name is required",
  ENGLISH_LANGUAGE_REQUIRED: "English language is required, because it is default language",
  CATEGORY_CREATED: "Category was successfully created.",
  CATEGORY_CREATION_FAILED: "Failed to create shop category",
  CATEGORY_ALREADY_CREATED: "Category name ${category_name} is already created",
  CATEGORY_Id_REQUIRED: "Category ID is required",
  CATEGORY_NOT_FOUND: "Category not found",
  CATEGORY_UPDATED: "Category Update successfully",
};

export default GENERIC_RESPONSE_MESSAGES;
